'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Play,Pause,Volume2,VolumeX,Maximize,Minimize,Settings2,X,ChevronRight,Radio,RotateCcw,MoveUpRight,Navigation,Crosshair,Shield,Orbit,Info,Check} from 'lucide-react';
import type {MissionEngine,FlightState} from './experience/engine';
import {CHAPTERS,DURATION,transmissionAt} from './experience/engine';
const initial:FlightState={ready:false,time:0,started:false,paused:false,autopilot:true,phase:'THE APPROACH',objective:'Rendezvous with Red Squadron.',speed:680,shield:100,lock:0,torpedoes:2,kills:0,fps:60,complete:false,message:'',roll:0,damage:0,quality:'balanced',targetX:.5,targetY:.43};
const format=(t:number)=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
export default function Home(){
 const world=useRef<HTMLDivElement>(null);const engine=useRef<MissionEngine|null>(null);const modalPaused=useRef(false);const [flight,setFlight]=useState(initial);const [sound,setSound]=useState(false);const [fullscreen,setFullscreen]=useState(false);const [settings,setSettings]=useState(false);const [briefing,setBriefing]=useState(false);const [motion,setMotion]=useState(true);const [error,setError]=useState('');const [chapterMenu,setChapterMenu]=useState(false);
 useEffect(()=>{let disposed=false;import('./experience/engine').then(({MissionEngine})=>{if(disposed||!world.current)return;try{engine.current=new MissionEngine(world.current,setFlight)}catch(e){setError(e instanceof Error?e.message:'Your browser could not start WebGL.')}});return()=>{disposed=true;engine.current?.dispose();engine.current=null}},[]);
 useEffect(()=>{if(settings||briefing){if(engine.current?.state.started&&!engine.current.state.paused&&!engine.current.state.complete){modalPaused.current=true;engine.current.pause()}}else if(modalPaused.current){modalPaused.current=false;if(engine.current?.state.paused)engine.current.pause()}},[settings,briefing]);
 useEffect(()=>{const cb=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',cb);return()=>document.removeEventListener('fullscreenchange',cb)},[]);
 const start=(auto:boolean)=>{engine.current?.start(auto);setSound(true)};
 const toggleSound=async()=>{if(!engine.current)return;if(!sound){await engine.current.audio.enable()}else engine.current.audio.mute(true);setSound(!sound)};
 const toggleFull=()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>setError('Fullscreen is unavailable in this browser window.'))};
 const current=transmissionAt(flight.time);const inTrench=flight.time>=68&&flight.time<137;const targeting=flight.time>=120&&flight.time<137;
 const seek=(t:number)=>{engine.current?.seek(t);setChapterMenu(false)};
 return <main className={`experience ${flight.started?'in-flight':''} ${flight.complete?'complete':''}`}>
  <div className="world" ref={world} aria-label="Real-time three dimensional space battle" />
  {!flight.ready&&<div className="preview-space"><div className="preview-planet" /></div>}
  <div className="scrim" />
  <div className="film-line" />
  <header className="topbar">
   <button className="brand" aria-label="Return to mission briefing" onClick={()=>engine.current?.home()}><span className="brand-mark"><Orbit size={38} strokeWidth={1.3}/></span><span>ROGUE<span className="brand-sub">SQUADRON</span></span></button>
   <div className="system-status"><i /> {flight.started?'RED FIVE · FLIGHT SYSTEMS ONLINE':'ALL SYSTEMS OPERATIONAL'}</div>
   <button className="icon-button" title={sound?'Mute audio':'Enable audio'} aria-label={sound?'Mute audio':'Enable audio'} onClick={toggleSound}>{sound?<Volume2 size={15}/>:<VolumeX size={15}/>}</button>
   <button className="icon-button desktop-icon" title="Fullscreen" aria-label="Toggle fullscreen" onClick={toggleFull}>{fullscreen?<Minimize size={15}/>:<Maximize size={15}/>}</button>
   <button className="icon-button" title="Settings" aria-label="Open settings" onClick={()=>setSettings(true)}><Settings2 size={15}/></button>
  </header>
  {!flight.started?<>
   <section className="hero-copy">
    <div className="eyebrow"><span /> AN INTERACTIVE SPACE ODYSSEY</div>
    <h1>THE BATTLE<br />OF <em>YAVIN.</em></h1>
    <p>One squadron. One impossible shot.<br />The fate of the galaxy is in your hands.</p>
    <div className="hero-actions"><button className="primary" disabled={!flight.ready} onClick={()=>start(false)}>{flight.ready?'LAUNCH MISSION':'PREPARING FLIGHT'} <ArrowUpRight size={18}/></button><button className="secondary" disabled={!flight.ready} onClick={()=>start(true)}><Play size={12} fill="currentColor"/> WATCH CINEMATIC</button></div>
    <div className="hero-detail"><span>03:10 <small>MISSION DURATION</small></span><b/><span>RED FIVE <small>YOUR CALLSIGN</small></span><button onClick={()=>setBriefing(true)} className="briefing-link">MISSION BRIEF <ArrowUpRight size={12}/></button></div>
   </section>
   <div className="station-label"><span className="locator"/><div>DS–1 ORBITAL BATTLE STATION<small>YAVIN SYSTEM <span>•</span> 160 KM DIAMETER</small></div></div>
   <aside className="mission-index"><span className="eyebrow">MISSION 01 / YAVIN IV</span><h3>A NEW HOPE.</h3>{['THE APPROACH','THE INTERCEPTION','THE TRENCH RUN','THE LAST SHOT'].map((x,i)=><div key={x} className={`phase-row ${i===0?'active':''}`}><span>0{i+1}</span>{x}{i===0&&<i/>}</div>)}<span className="index-line"/></aside>
   <footer className="landing-footer"><span className="footer-label">FLIGHT CONTROLS</span><div><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><span>STEER</span></div><div><kbd>SHIFT</kbd><span>BOOST</span></div><div><kbd>SPACE</kbd><span>FIRE</span></div><div className="torpedo-key"><kbd>T</kbd><span>TORPEDOES</span></div><p>THE FORCE WILL BE WITH YOU. ALWAYS.</p></footer>
  </>:<>
   <section className="flight-heading"><div className="eyebrow"><span/> MISSION 01 <b>/</b> {String(CHAPTERS.filter(x=>x.time<=flight.time).length).padStart(2,'0')}</div><h2>{flight.phase}</h2><p>{flight.objective}</p></section>
   <div className="flight-top-right"><span className="callsign">RED FIVE</span><span className="flight-mode"><i/>{flight.autopilot?'CINEMATIC AUTOPILOT':inTrench?'MANUAL FLIGHT':'FORMATION ASSIST'}</span></div>
   {inTrench&&<div style={{left:`${flight.targetX*100}%`,top:`${flight.targetY*100}%`}} className={`target-hud ${targeting?'targeting':''} ${flight.lock>=.98?'locked':''}`}><div className="target-corner tl"/><div className="target-corner tr"/><div className="target-corner bl"/><div className="target-corner br"/><div className="reticle-core"><span/><span/></div><div className="target-range">{targeting?'EXHAUST PORT · 2 M':'COMBAT GUIDANCE'}</div>{targeting&&<><div className="lock-track"><i style={{width:`${flight.lock*100}%`}}/></div><div className="lock-value">{flight.lock>=.98?'TARGET LOCKED · PRESS T':`ACQUIRING ${Math.round(flight.lock*100)}%`}</div></>}</div>}
   {inTrench&&<><div className="altitude-gauge"><span>ALT</span>{[30,20,10,0].map(x=><div key={x}><i/>{x}</div>)}<b/></div><div className="speed-gauge"><span>THR</span>{[100,75,50,25,0].map(x=><div key={x}><i/>{x}</div>)}</div></>}
   {current&&!flight.complete&&<div className="transmission" key={current.t}><div className="radio-icon"><Radio size={17}/><div className="radio-wave">{[4,12,7,18,9,14,5].map((h,i)=><i key={i} style={{height:h,animationDelay:`${i*.1}s`}}/>)}</div></div><div><span>{current.who}<small>COMMS CHANNEL 01</small></span><p>{current.line}</p></div></div>}
   {flight.paused&&!settings&&!briefing&&<div className="pause-overlay"><span className="eyebrow">FLIGHT SUSPENDED</span><h2>HOLDING POSITION.</h2><button className="primary" onClick={()=>engine.current?.pause()}><Play size={13}/> RESUME MISSION</button><button className="text-button" onClick={()=>engine.current?.home()}>RETURN TO BRIEFING</button></div>}
   {!flight.complete&&<div className="flight-bottom">
    <div className="telemetry"><div className="telemetry-speed"><span>VELOCITY <small>MGLT</small></span><strong>{flight.speed.toLocaleString()}</strong><div className="speed-bars">{Array.from({length:22},(_,i)=><i key={i} className={i<Math.min(22,flight.speed/70)?'on':''}/>)}</div></div><div className="telemetry-shield"><span><Shield size={11}/> SHIELDS</span><strong>{Math.round(flight.shield)}<small>%</small></strong><div className="shield-track"><i style={{width:`${flight.shield}%`}}/></div></div><div className="telemetry-torpedoes"><span>PROTON TORPEDOES</span><strong><i className={flight.torpedoes?'loaded':''}/><i className={flight.torpedoes?'loaded':''}/><small>{flight.torpedoes.toString().padStart(2,'0')} / 02</small></strong></div><div className="flight-actions"><button className={`mode-button ${flight.autopilot?'selected':''}`} onClick={()=>engine.current?.setAutopilot(!flight.autopilot)}><Navigation size={12}/>{flight.autopilot?'AUTOPILOT ON':'AUTOPILOT OFF'}<kbd>C</kbd></button>{inTrench&&<button className="mode-button" onClick={()=>{engine.current?.setKey('Space',true);setTimeout(()=>engine.current?.setKey('Space',false),180)}}><Crosshair size={12}/> FIRE LASERS</button>}{targeting&&flight.lock>=.98&&<button className="mode-button fire-torpedo" onClick={()=>engine.current?.fireTorpedoes()}>FIRE TORPEDOES <kbd>T</kbd></button>}</div></div>
    <div className="timeline-bar"><button className="play-toggle" onClick={()=>engine.current?.pause()} aria-label={flight.paused?'Resume mission':'Pause mission'}>{flight.paused?<Play size={13}/>:<Pause size={13}/>}</button><span className="time-code">{format(flight.time)}<small> / {format(DURATION)}</small></span><input aria-label="Mission timeline" className="timeline" type="range" min="0" max="189" step=".1" value={flight.time} style={{'--progress':`${flight.time/DURATION*100}%`} as React.CSSProperties} onChange={e=>seek(Number(e.target.value))}/><button className="chapters-toggle" onClick={()=>setChapterMenu(!chapterMenu)}>CHAPTERS <ChevronRight size={12} className={chapterMenu?'rotated':''}/></button></div>
    {chapterMenu&&<div className="chapter-menu">{CHAPTERS.map((x,i)=><button key={x.time} onClick={()=>seek(x.time)}><span>0{i+1}</span>{x.name}<small>{format(x.time)}</small></button>)}</div>}
   </div>}
   {!flight.autopilot&&inTrench&&<div className="touch-controls"><div className="touch-stick" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();engine.current?.setPointer((e.clientX-r.left-r.width/2)/(r.width/2),(e.clientY-r.top-r.height/2)/(r.height/2),true)}} onPointerMove={e=>{if(e.buttons){const r=e.currentTarget.getBoundingClientRect();engine.current?.setPointer((e.clientX-r.left-r.width/2)/(r.width/2),(e.clientY-r.top-r.height/2)/(r.height/2),true)}}} onPointerUp={()=>engine.current?.setPointer(0,0,false)}><span>+</span></div><button onPointerDown={()=>engine.current?.setKey('ShiftLeft',true)} onPointerUp={()=>engine.current?.setKey('ShiftLeft',false)}>BOOST</button></div>}
   {flight.complete&&<section className="victory"><div className="victory-mark"><Check size={32}/></div><div className="eyebrow">MISSION ACCOMPLISHED</div><h2>A NEW HOPE.</h2><p>One shot changed the galaxy.</p><div className="victory-stats"><div><strong>DS–1</strong><span>TARGET DESTROYED</span></div><div><strong>{flight.kills.toString().padStart(2,'0')}</strong><span>FIGHTERS NEUTRALIZED</span></div><div><strong>{Math.round(flight.shield)}%</strong><span>SHIELDS REMAINING</span></div></div><div className="hero-actions"><button className="primary" onClick={()=>start(flight.autopilot)}><RotateCcw size={14}/> FLY AGAIN</button><button className="secondary" onClick={()=>engine.current?.home()}>RETURN TO BRIEFING</button></div></section>}
  </>}
  {error&&<div className="error-notice"><Info size={18}/><p>{error}</p><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={14}/></button></div>}
  {(settings||briefing)&&<div className="modal-backdrop" onClick={()=>{setSettings(false);setBriefing(false)}}><section className="modal" role="dialog" aria-modal="true" aria-label={settings?'Flight settings':'Mission briefing'} onClick={e=>e.stopPropagation()}><button className="close-modal icon-button" onClick={()=>{setSettings(false);setBriefing(false)}} aria-label="Close dialog"><X size={16}/></button><div className="eyebrow"><span/>{settings?'CONFIGURE YOUR FLIGHT':'CLASSIFIED · REBEL ALLIANCE'}</div><h2>{settings?'FLIGHT SETTINGS.':'ONE IMPOSSIBLE SHOT.'}</h2>{settings?<><div className="setting-row"><div><strong>Visual quality</strong><p>Choose a balance of detail and performance.</p></div><select aria-label="Visual quality" value={flight.quality} onChange={e=>engine.current?.setQuality(e.target.value)}><option value="high">High</option><option value="balanced">Balanced</option><option value="performance">Performance</option></select></div><div className="setting-row"><div><strong>Cinematic camera motion</strong><p>Camera shake and banking during combat.</p></div><button role="switch" aria-checked={motion} className={`switch ${motion?'on':''}`} onClick={()=>{setMotion(!motion);engine.current?.setMotion(!motion)}}><i/></button></div><div className="setting-row"><div><strong>Audio</strong><p>Original synthesized score, engines and weapons.</p></div><button role="switch" aria-checked={sound} className={`switch ${sound?'on':''}`} onClick={toggleSound}><i/></button></div><div className="controls-grid">{[['W A S D / ↑ ↓ ← →','STEER'],['Q / E','ROLL'],['SHIFT','BOOST'],['SPACE','FIRE LASERS'],['T','PROTON TORPEDOES'],['C','TOGGLE AUTOPILOT'],['P / ESC','PAUSE']].map(([key,label])=><div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div></>:<><p className="briefing-intro">An Imperial battle station is closing on the Rebel base. Its defenses are designed for a large-scale assault. A small, one-man fighter can slip through.</p><div className="brief-objective"><Crosshair size={23}/><div><strong>THE TARGET</strong><p>A two-meter thermal exhaust port, directly above the main reactor. A precise proton torpedo strike will start a chain reaction.</p></div></div><div className="brief-objective"><Navigation size={23}/><div><strong>YOUR APPROACH</strong><p>Join Red Squadron, break through the fighter screen, and descend into the equatorial trench. Manual flight begins in the trench. Stay centered for a stable targeting lock.</p></div></div><div className="brief-objective"><Shield size={23}/><div><strong>FLIGHT ASSIST</strong><p>Toggle autopilot at any time with C. Navigation assistance keeps the mission moving, and the torpedo computer takes the final shot if you need support.</p></div></div><button className="primary" disabled={!flight.ready} onClick={()=>{setBriefing(false);start(false)}}>READY, RED FIVE <ArrowUpRight size={16}/></button></>}</section></div>}
 </main>
}
